name: Docker CD

on: push

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read

    strategy:
      fail-fast: false
      matrix:
        language: [javascript]

    # Specify the container in which actions will run
    container:
      image: ghcr.io/demo-teams/github-actions-for-packages/tic-tac-toe:sha-8882412
      
      

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
   
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}
   
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: npm install and build webpack
      run: |
        npm install
        npm run build
    - uses: actions/upload-artifact@main
      with:
        name: webpack artifacts
        path: public/

   
